### ISSUE TITLE
QQ: setting shows to pause based on directory

### ISSUE THREAD

**Issue by mgaulton** [derkens/scripts#10]
I need to migrate a group of shows between NAS and rather than pick through the list and pause them, wondering if you can think of a way to do it through the api?

/mnt/newtv/@Sorted -> /mnt/mybookb/tv

**Comment by derkens** [comment]
should be possible, tomorrow I have some time to look at this.

**Comment by derkens** [comment]
I've found some time, this should work:
[https://gist.github.com/derkens/8d5a609a9d305b60f982a975c3b6d895](url)
every show in /mnt/newtv/ should be paused when running it. No integration with my other scripts so you have to fill in the details.

**Comment by mgaulton** [comment]
Sweet. I got it sorted now. thank you kindly.
