### ISSUE TITLE
405 method not ssupport

### ISSUE THREAD

**Issue by mgaulton** [derkens/scripts#7]
Is there a minimum required config for this to work? I don't want any notifiers so they aren't configured. Setup the info for SB but i get this regardless of which script i attempt. The url works manually in the browser with no issue.

server5:/opt/code/sbscripts # python sickbeard-snatched2wanted.py
INFO      - Loading config from settings.cfg
INFO      - Opening URL: http://localhost:8182/api/2b05e4af60399e6bfd4245bc6bb39b97/?
Traceback (most recent call last):
  File "sickbeard-snatched2wanted.py", line 29, in <module>
    t = urllib2.urlopen(url, params).read()
  File "/usr/lib64/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 405: Method Not Allowed

**Comment by derkens** [comment]
Hi, sorry you are having issues, to debug this could you:
- try the url with curl on the cli?
- check your python version
- post the sb part of your settings.cfg

I've turned off all notifications and not getting any error, we should test with the snatched2wanted script, the other script are notification only scripts.
I don't have eps with status snatched right now, so testing is limited, until next broadcasts. ;)

**Comment by mgaulton** [comment]
Python is 2.7.8 . curl returns the json contents correctly. The SB
part of the config

[SickBeard]
#mandatory:
host=localhost
port=8182
api_key=api
web_root=/
ssl=0
app_token=OKCXmkvHN1syU2e8xvpefTnyvVWGv5
#(pushover) took app token from sickbeard, if U use your own, replace

**Comment by derkens** [comment]
could you try this in your browser?
http://localhost:8182/sickbeard/api/2b05e4af60399e6bfd4245bc6bb39b97/?cmd=history&type=snatched&limit=2

**Comment by mgaulton** [comment]
Ok, i just realized you might need to know, i'm using latest master of SickRage.

that link took me to the show list. I believe that's because i have nothing in snatched status at the moment.

**Comment by derkens** [comment]
ok, never tested this with sickrage, could you change "snatched" to "downloaded" and try again?

**Comment by mgaulton** [comment]
http://localhost:8182/sickbeard/api/2b05e4af60399e6bfd4245bc6bb39b97/?cmd=history&type=downloaded&limit=2

This seemed to have just taken me back to the showlist. Don't worry about it, I don't want to spend too much of your time on this.

**Comment by derkens** [comment]
ok, seems that the sickrage api is different, maybe in the future we will adapt this to sickrage, for the moment I can't really find any api documentation? No worries here :D I wish I could have solved my first issue ;)

**Comment by mgaulton** [comment]
No worry, I was thinking of picking apart nzbToMedia and seeing if it had a method when i stumbled on your script :) thanks for the help.

**Comment by derkens** [comment]
ok no problem, good luck, closing this for now.
