### ISSUE TITLE
QQ/Request: ignore ended, but incomplete shows

### ISSUE THREAD

**Issue by mgaulton** [derkens/scripts#8]
Hey there, 

I love your scripts, i've been thinking/looking for something like this for a while. I'm just wondering if there is a way to make it so that if a show is ended but not all episodes are downloaded, that it doesn't get paused.  That's the only quirck I found.

Thanks

**Comment by derkens** [comment]
ok, sorry I haven't responded to this, somehow I did not get a notification.
Are you referring to older shows? For new shows that get cancelled, if there is a next episode date, the show will not be paused. So it should work untill the last ep is downloaded.

**Comment by derkens** [comment]
So, I have thought this over, and indeed, if I add an older already cancelled show, this is not working right.
I have a commit ready heavely based on your (closed?) pull request.

Nice to hear somebody likes my scripts :smile:

**Comment by mgaulton** [comment]
So i tweaked on my end
https://github.com/mgaulton/one-offs/blob/master/sickbeard-cancelled-rev.py

**Comment by derkens** [comment]
I added one of your shows, and I think I've fixed it. Not sure what else will break now, though... :smile: 
commit in a minute...

**Comment by mgaulton** [comment]
Awesome. I created and closed the PR cause I had some other ideas I was going to play with lol

**Comment by mgaulton** [comment]
So, I thought i would throw this at you and see what you thought. i ran into a case where a show i had was completed but some of the episodes got turned back to wanted through nzbToMedia. So i tweaked it to recheck and restart any that were paused but status has changed. I threw in a .refresh since it could be that the show just hasn't picked up on the files. 

if unaired == 0 and (total - totaldwl > 0):
		logger.logging.info(showname + " has status Ended, but not all episodes are downloaded")
		params2 = {'cmd': 'show.pause', indexer: sickid, 'pause': 0}
		res2 = api.sick_call(params2)
		params3 = {'cmd': 'show.refresh', indexer: sickid}
		res3 = api.sick_call(params3)
	if unaired == 0 and (total - totaldwl == 0) and totalsnt == 0:
		logger.logging.debug(showname + " has " + indexer + " " + str(sickid))
		params = {'cmd': 'show.pause', indexer: sickid, 'pause': 1}
		res = api.sick_call(params)
		params3 = {'cmd': 'show.refresh', indexer: sickid}
		res3 = api.sick_call(params3)
		args = {'showname': showname.encode("utf-8")}

**Comment by derkens** [comment]
Ok, looks nice, though I never thought there would be so many exceptions.
Maybe we should rethink this. 
Currently I'm setting the show to paused to get notified just once.
Perhaps we should track which show have been ended and notified, without setting the shows to pause. (I have a pickle in place...) Then Sickrage can still do it's job, getting propers for example. 
Just for my curiousity: why would nzbtomedia set a downloaded episode back to wanted?

**Comment by mgaulton** [comment]
I've been playing with nzbgeek.info, which has direct couch and sickrage importing. when i set it up, it didn't check what eps i already had, it just said "cool, new show, push all the nzbz" and when those failed mostly due to being older etc, NTM still ran and since SR doesn't say " I already have that one, what are you doing " and ignore it, it still sets it to failed even though the file exists already
I like the pause idea. i'm less worried about propers if a show is complete. SR does a thing now where if the original file isn't in the history, it ignores the proper anyway so older propers won't work a lot of the time. Especially if you've rebuilt or purged the dbs for some reason. (i've rebuilt the machine a while back so lost all the historical.)

**Comment by derkens** [comment]
So I've found some time to change from pausing the show, to saving the tvdbid to a pickle. Now sickrage can do whatever it wants to ended shows. In my usercase: sr can still download a proper if it found one for a recently ended show. You can put shows on pause yourself, the check is not getting paused shows from the api.

**Comment by mgaulton** [comment]
So you're just getting notices now and not touching the shows?

**Comment by derkens** [comment]
Correct.
